Fix issue #265
vmware/power-validated-solutions-for-cloud-foundation pull request #327
Opened 2023-08-15 16:22 UTC by jshiplett

### Summary

Bugfix for issue 265

### Type

- [x] Bugfix
- [ ] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [ ] Documentation has been added or updated.

Tested functionality for adding new permissions onto a vSphere Namespace.

### Issue References

Closes #265 

### Additional Information

None

2023-08-15 20:55 UTC, tenthirtyam requested changes
Minor changes requested to use the `//TODO`syntax so that these can be marked for future updates.

2023-08-15 20:55 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +                                            #Temp fix until Get-WMNamespacePermission is fixed
May be good to use the `//TODO`syntax here so that this can be marked for future updates.

2023-08-15 20:55 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +                                                #Temp fix until New-WMNamespacePermission is fixed
May be good to use the `//TODO`syntax here so that this can be marked for future updates.

2023-08-15 20:56 UTC, tenthirtyam commented
I'll address the failed action.

2023-08-16 01:27 UTC, tenthirtyam commented
Closed/opened to force the action to rerun fresh.

2023-08-16 01:31 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +                                                #Temp fix until New-WMNamespacePermission is fixed
```suggestion
                                                # TODO: A temporary fix until New-WMNamespacePermission is fixed.
```

2023-08-16 01:31 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +                                            #Temp fix until Get-WMNamespacePermission is fixed
```suggestion
                                            # TODO: A temporary fix until New-WMNamespacePermission is fixed.
```

2023-08-17 12:56 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +                                            #Temp fix until Get-WMNamespacePermission is fixed
Resolved in https://github.com/vmware/power-validated-solutions-for-cloud-foundation/pull/327/commits/da5da7423b13ff9cc270529bd0e92c09fe714928.

2023-08-17 13:02 UTC, tenthirtyam approved these changes
LGTM

2023-08-17 13:05 UTC, tenthirtyam commented
Rebased and changes applied. The use of a TODO makes it easier to track for technical debt.

<img width="819" alt="image" src="https://github.com/vmware/power-validated-solutions-for-cloud-foundation/assets/7771363/8c1d4190-8777-4a51-9ff7-2d952690fa98">

2023-08-17 13:23 UTC, GaryJBlake approved these changes
LGTM!

2023-08-17 13:24 UTC, merged