feat: added Get-vRLSCMProductPassword Function
vmware/power-validated-solutions-for-cloud-foundation pull request #491
Opened 2024-02-08 14:53 UTC by burnsjared0415

### Summary
Created new function to ` Get-vRSLCMProductPassword ` to be used in Power Management to get Locker Password and decrypted for the ability to login in.

### Type

- [ ] Bugfix
- [x] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [x] Documentation has been added or updated.

### Issue References

### Additional Information

2024-02-08 15:07 UTC, GaryJBlake requested changes

2024-02-08 15:07 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        $response
Trying to not have an extra variable here for newer functions as its overkill

2024-02-08 15:07 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Get-vRSLCMProductPassword -lockervmid 8de0ae90-b2ac-48b8-a5c3-d16e3254298b -vrslcmrootpass VMw@re1!
```suggestion
        Get-vRSLCMProductPassword -lockerVmid 8de0ae90-b2ac-48b8-a5c3-d16e3254298b -vrslcmRootPass VMw@re1!
```

2024-02-08 15:07 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$lockervmid,
```suggestion
        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$lockerVmid,
```

2024-02-08 15:07 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$vrslcmrootpass
```suggestion
        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$vrslcmRootPass
```

2024-02-08 15:07 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Get Product Password in VMware Aria Suite Lifecycle
```suggestion
        Get Product Password from VMware Aria Suite Lifecycle
```

2024-02-08 15:07 UTC, GaryJBlake commented on docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductPassword.md
> +Get Product Password in VMware Aria Suite Lifecycle
```suggestion
Get Product Password from VMware Aria Suite Lifecycle

```

2024-02-08 15:07 UTC, GaryJBlake commented on docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductPassword.md
> +This example gets all environments in VMware Aria Suite Lifecycle
```suggestion
This example retrieves the product password based on the vmid provided

```

2024-02-08 15:30 UTC, tenthirtyam commented on docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductPassword.md
> +This example gets all environments in VMware Aria Suite Lifecycle
Resolved in cd4ef29.

2024-02-08 15:30 UTC, tenthirtyam commented on docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductPassword.md
> +Get Product Password in VMware Aria Suite Lifecycle
Resolved in cd4ef29.

2024-02-08 15:30 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +        Get Product Password in VMware Aria Suite Lifecycle
Resolved in cd4ef29.

2024-02-08 15:30 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$lockervmid,
Resolved in cd4ef29.

2024-02-08 15:30 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +        Get-vRSLCMProductPassword -lockervmid 8de0ae90-b2ac-48b8-a5c3-d16e3254298b -vrslcmrootpass VMw@re1!
Resolved in cd4ef29.

2024-02-08 15:30 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +        This example gets all environments in VMware Aria Suite Lifecycle
Resolved in cd4ef29.

2024-02-08 15:31 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +        $response
Resolved in cd4ef29.

2024-02-08 15:37 UTC, tenthirtyam commented on docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductPassword.md
> +```
Resolved in ad1b306.

2024-02-09 20:26 UTC, tenthirtyam approved these changes
LGTM!

2024-02-09 20:27 UTC, merged