feat: configure nsx global manager mode(active or standby)
vmware/power-validated-solutions-for-cloud-foundation pull request #727
Opened 2024-08-21 12:00 UTC by slakshmanan2706

- Added `Set-NsxtGloblaManagerActive` cmdlet to configure the NSX Global Manager to Active mode.
- Added `Set-NsxtGloblaManagerStandby` cmdlet to configure the NSX Global Manager to standby mode.
- Added `Test-NsxVersionCompatibility` cmdlet to check the NSX version compatibility between the active and standby NSX Global Manager.
- Added `Get-NsxtGlobalManagerMode` cmdlet to retrieve the mode of the NSX Global Manager.
- Added `Add-NsxtGlobalManagerMode` cmdlet to configure the NSX Global Manager to Active or Standby mode.

### Summary

### Type

- [ ] Bugfix
- [x] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### Test and Documentation

- [x] Tests have been completed.
- [ ] Documentation has been added or updated.

### Issue References

### Additional Information

2024-08-21 12:38 UTC, GaryJBlake requested changes

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +            }
Remove this code, we have not typically added Write-Output to API functions

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $response = Invoke-RestMethod -Uri $uri -Method PATCH -Headers $nsxtHeaders -body $body -SkipCertificateCheck
```suggestion
                Invoke-RestMethod -Uri $uri -Method PATCH -Headers $nsxtHeaders -body $body -SkipCertificateCheck 
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Set-NsxtGloblaManagerActive -displayName "SF001"
```suggestion
        Set-NsxtGloblaManagerActive -displayName sfo-m01-nsx-gm01 
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Set-NsxtGloblaManagerActive -displayName "SF001"
Let's use the PnP values and not the one's Hari defined in his code

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        This example configures the NSX Global Manager to Active mode with the display name SFO01.
```suggestion
        This example sets the NSX Global Manager to Active mode with the display name sfo-m01-nsx-gm01.
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Set-NsxtGlobalManagerMode -displayName "LAX01" -standbyServer  "lax-m01-nsx-gm01.lax.rainpole.io" -standbyServerUser admin -standbyServerPass "VMw@re123!VMw@re123!"
```suggestion
        Set-NsxtGlobalManagerMode -displayName lax-m01-nsx-gm01 -standbyServer  "lax-m01-nsx-gm01.lax.rainpole.io" -standbyServerUser admin -standbyServerPass "VMw@re1!VMw@re1!"
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Set-NsxtGlobalManagerMode -displayName "LAX01" -standbyServer  "lax-m01-nsx-gm01.lax.rainpole.io" -standbyServerUser admin -standbyServerPass "VMw@re123!VMw@re123!"
Let's use PnP values and passwords that match all the other functions

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +            }
Remove as per other comment

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $response = Invoke-RestMethod -Uri $uri -Method PUT -Headers $Global:nsxtHeaders -body $body -SkipCertificateCheck
```suggestion
                Invoke-RestMethod -Uri $uri -Method PUT -Headers $Global:nsxtHeaders -body $body -SkipCertificateCheck 
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Test-NsxVersionCompatibility -standbyServer  "lax-m01-nsx-gm01.lax.rainpole.io" -standbyServerUser admin -standbyServerPass "VMw@re123!VMw@re123!"
```suggestion
        Test-NsxVersionCompatibility -standbyServer  "lax-m01-nsx-gm01.lax.rainpole.io" -standbyServerUser admin -standbyServerPass "VMw@re1!VMw@re1!"
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $gmnodethumbprint = (Get-SHA256Thumbprint -url "https://$standbyServer").replace(":", "")
```suggestion
                $gmNodeThumbprint = (Get-SHA256Thumbprint -url "https://$standbyServer").replace(":", "")
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $connection_info = New-Object -TypeName psobject
```suggestion
                $connectionDetails = New-Object -TypeName psobject
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $connection_info | Add-Member -Notepropertyname 'fqdn' -Notepropertyvalue $standbyServer
```suggestion
                $connectionDetails | Add-Member -Notepropertyname 'fqdn' -Notepropertyvalue $standbyServer
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $connection_info | Add-Member -Notepropertyname 'username' -Notepropertyvalue $user
```suggestion
                $connectionDetails | Add-Member -Notepropertyname 'username' -Notepropertyvalue $user
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $connection_info | Add-Member -Notepropertyname 'password' -Notepropertyvalue $pass
```suggestion
                $connectionDetails | Add-Member -Notepropertyname 'password' -Notepropertyvalue $pass
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $connection_info | Add-Member -Notepropertyname 'thumbprint' -Notepropertyvalue $gmnodethumbprint
```suggestion
                $connectionDetails | Add-Member -Notepropertyname 'thumbprint' -Notepropertyvalue $gmNodeThumbprint
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $conn_info = @()
```suggestion
                $connection = @()
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $conn_info += $connection_info
```suggestion
                $connection += $connectionDetails
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +                $body | Add-Member -Notepropertyname 'connection_info' -Notepropertyvalue $conn_info
```suggestion
                $body | Add-Member -Notepropertyname 'connection_info' -Notepropertyvalue $connection
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +Function Test-NsxVersionCompatibility {
This same function can be used to check the compatability for standby and Active. Change inputs to fqdn, username and password

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Get-NsxtGlobalManagerMode -displayName "SF001"
```suggestion
        Get-NsxtGlobalManagerMode -displayName sfo-m01-nsx-gm01
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        Add-NsxtGlobalManagerMode -server sfo-m01-nsx-gm01.sfo.rainpole.io -user admin -pass "VMw@re123!VMw@re123!" -gmMode STANDBY -displayName LAX01 -standbyServer sfo-m01-nsx-gm01c.sfo.rainpole.io
```suggestion
        Add-NsxtGlobalManagerMode -server sfo-m01-nsx-gm01.sfo.rainpole.io -user admin -pass "VMw@re1!VMw@re1!" -gmMode STANDBY -displayName lax-m01-nsx-gm01 -standbyServer lax-m01-nsx-gm01c.lax.rainpole.io -standbyServerUser admin1 -standbyServerPass "VMw@re1!VMw@re1!"
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        This example configures the virtual IP address of the NSX Global Manager cluster.
Example description needs correcting

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        .EXAMPLE
We should add an example for setting the ACTIVE node too

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        .PARAMETER gmMode
Just use mode no need for gm at the front

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +        if (Test-NSXTConnection -server $server) {
```suggestion
        if (Test-NsxtConnection -server $server) {
```

2024-08-21 12:38 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +            if (Test-NSXTAuthentication -server $server -user $user -pass $pass) {
```suggestion
            if (Test-NsxtAuthentication -server $server -user $user -pass $pass) {
```

2024-08-21 19:09 UTC, tenthirtyam requested changes
- [ ] Update the module manifest build.
- [ ] Update the module manifiest with required function exports.
- [ ] Add the documentation for each exported function.
- [ ] Update the `CHANGELOG.md` if targets for v2.12.0.

2024-08-22 10:05 UTC, GaryJBlake approved these changes
LGTM!

2024-08-22 10:08 UTC, merged